apiVersion: apps/v1
kind: Deployment
metadata:
  name: clouddevops-capstone
  labels:
    app: clouddevops-capstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clouddevops-capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: clouddevops-capstone
    spec:
      containers:
        - image: bkocis/clouddevops-capstone
          imagePullPolicy: Always
          name: clouddevops-capstone
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: clouddevops-capstone
  labels:
    app: clouddevops-capstone
spec:
  type: LoadBalancer
  selector:
    app: clouddevops-capstone
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30000
      protocol: TCP